<?php

/**
 * @file
 * Primary module hooks for Neo | Favicon module.
 */

/**
 * Implements hook_page_attachments_alter().
 */
function neo_favicon_page_attachments_alter(array &$attachments) {
  /** @var \Drupal\neo_favicon\FaviconManager $manager */
  $manager = \Drupal::service('neo_favicon.manager');
  $html = $manager->getHtml();
  if (!empty($html)) {
    // Remove default favicon from html_head_link.
    if (!empty($attachments['#attached']['html_head_link'])) {
      foreach ($attachments['#attached']['html_head_link'] as $i => $item) {
        if (!empty($item) && is_array($item)) {
          foreach ($item as $ii => $iitem) {
            if (isset($iitem['rel']) && in_array($iitem['rel'], [
              'shortcut icon',
              'icon',
            ])) {
              unset($attachments['#attached']['html_head_link'][$i][$ii]);
            }
          }
          if (empty($attachments['#attached']['html_head_link'][$i])) {
            unset($attachments['#attached']['html_head_link'][$i]);
          }
        }
      }
      if (empty($attachments['#attached']['html_head_link'])) {
        unset($attachments['#attached']['html_head_link']);
      }
    }
    // Attach favicon tags.
    $attachments['#attached']['html_head'][] = [
      [
        '#type' => 'markup',
        '#markup' => $html,
        '#allowed_tags' => ['link', 'meta'],
        '#cache' => [
          'tags' => ['config:neo_favicon.settings'],
        ],
      ],
      'real_favicon',
    ];
  }
}

/**
 * Implements hook_theme().
 */
function neo_favicon_theme(): array {
  return [
    'neo_toolbar_element__favicon' => [
      'base hook' => 'neo_toolbar_element',
    ],
  ];
}
