<?php

/**
 * @file
 * Primary module hooks for Neo | Favicon module.
 */

use Drupal\Core\Entity\ContentEntityInterface;

/**
 * Implements hook_page_attachments_alter().
 */
function neo_favicon_page_attachments_alter(array &$attachments) {
  /** @var \Drupal\neo_favicon\FaviconManager $manager */
  $manager = \Drupal::service('neo_favicon.manager');
  $html = $manager->getHtml();
  if (!empty($html)) {
    // Remove default favicon from html_head_link.
    if (!empty($attachments['#attached']['html_head_link'])) {
      foreach ($attachments['#attached']['html_head_link'] as $i => $item) {
        if (!empty($item) && is_array($item)) {
          foreach ($item as $ii => $iitem) {
            if (isset($iitem['rel']) && in_array($iitem['rel'], [
              'shortcut icon',
              'icon',
            ])) {
              unset($attachments['#attached']['html_head_link'][$i][$ii]);
            }
          }
          if (empty($attachments['#attached']['html_head_link'][$i])) {
            unset($attachments['#attached']['html_head_link'][$i]);
          }
        }
      }
      if (empty($attachments['#attached']['html_head_link'])) {
        unset($attachments['#attached']['html_head_link']);
      }
    }
    // Attach favicon tags.
    $attachments['#attached']['html_head'][] = [
      [
        '#type' => 'markup',
        '#markup' => $html,
        '#allowed_tags' => ['link', 'meta'],
        '#cache' => [
          'tags' => ['config:neo_favicon.settings'],
        ],
      ],
      'real_favicon',
    ];
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function neo_favicon_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'neo_token_image' || $hook == 'neo_token_logo') {
    // Move my_module_form_alter() to the end of the list.
    $group = $implementations['neo_favicon'];
    unset($implementations['neo_favicon']);
    $implementations['neo_favicon'] = $group;
  }
}

/**
 * Implements hook_neo_token_logo_alter().
 */
function neo_favicon_neo_token_logo_alter(&$uri, &$params, ?ContentEntityInterface $entity = NULL) {
  // Will only run if the URI is not already set.
  if (!$uri) {
    /** @var \Drupal\neo_favicon\FaviconManager $manager */
    $manager = \Drupal::service('neo_favicon.manager');
    $largestImage = [];

    foreach ($manager->getImages() as $imageUri => $dimensions) {
      $size = $dimensions['width'] * $dimensions['height'];
      if (empty($largestImage) || $size > ($largestImage['size'] ?? 0)) {
        $largestImage = [
          'uri' => $imageUri,
          'size' => $size,
        ];
      }
    }

    $uri = $largestImage['uri'] ?? NULL;
  }
}

/**
 * Implements hook_neo_token_image_alter().
 */
function neo_favicon_neo_token_image_alter(&$uri, &$params, ?ContentEntityInterface $entity = NULL) {
  neo_favicon_neo_token_logo_alter($uri, $params, $entity);
}
