# Schema for the configuration files of the Neo | Favicon module.
neo_favicon.settings:
  type: config_object
  label: 'Neo | Favicon settings'
  mapping:
    file:
      type: string
      label: 'File'
    tags:
      type: string
      label: 'Tags'

neo_toolbar_item.settings.favicon:
  type: neo_toolbar_item_settings
  mapping:
    url:
      type: string
      label: URL
    target:
      type: boolean
      label: Open in new window
    image:
      type: string
      label: Image
    scheme:
      type: string
      label: Color Scheme
    filter:
      type: string
      label: Filter
