# Schema for the configuration files of the Neo | Favicon module.
neo_favicon.settings:
  type: config_object
  label: 'Neo | Favicon settings'
  mapping:
    file:
      type: string
      label: 'File'
    tags:
      type: text
      label: 'Tags'
